export const CONSTANT_PATN = "blog-starter";
export const CMS_NAME = "Markdown";
export const WEB_TITLE = "Ai.Haibara codes";
export const HOME_OG_IMAGE_URL =
  "https://og-image.vercel.app/Next.js%20Blog%20Starter%20Example.png?theme=light&md=1&fontSize=100px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg";
export const ABOUT_SLUG = "about.md";

export const MOUSE_CONTENT = [
  "❤去活出你自己。❤",
  "❤《日不落》❤",
  "❤《一格格》❤",
  "❤《森林巴士》❤",
  "❤《爱就一个字》❤",
  "❤《星辰大海》❤",
  "❤《千千万万》❤",
  "❤《我在等》❤",
  "❤《如一》❤",
  "❤《收敛》❤",
  "❤《间距》❤",
  "❤《早点早点》❤",
  "❤《阿拉斯加海湾》❤",
  "❤《Peace&Love》❤",
  "❤《灰色》❤",
  "❤《带你回家》❤",
  "❤《等我回家》❤",
  "❤《0919》❤",
  "❤《我很好》❤",
  "❤《会不会》❤",
  "❤《经济舱》❤",
  "❤《我走后》❤",
  "❤《不删》❤",
  "❤《Girls》❤",
  "❤《Let Her Go》❤",
  "❤《关于你的梦》❤",
  "❤《慢慢》❤",
  "❤《下雨天》❤",
  "❤《翅膀》❤",
  "❤《靠近一点》❤",
  "❤《翅膀》❤",
  "❤《This Is Love》❤",
  "❤《重来》❤",
  "❤《晴天》❤",
  "❤《空白格》❤",
  "❤《爱你3000》❤",
  "❤《下落不明》❤",
  "❤《我要》❤",
  "❤《晚星》❤",
  "❤《你，好不好？》❤",
  "❤《50 Feet》❤",
  "❤《COCO》❤",
  "❤《NUMB》❤",
  "❤《重演》❤",
  "❤《所念皆星河》❤",
];
